# Generated by Django 4.2.6 on 2024-05-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebCommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contrasena',
            new_name='rut',
        ),
    ]
