# Generated by Django 4.2.2 on 2024-07-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCommerce', '0002_rename_contrasena_usuarios_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], max_length=10),
        ),
    ]
